### PR TITLE
Provide expansion utilities to write the response body

### PR DESCRIPTION
**Pull request by arteymix**
I'm wondering if the UTF-8 expansion should set the `charset` parameter for the `Content-Type` header.

The documentation should be updated as well.

Otherwise, it's ready to merge!

### CODE REVIEW

**Comment by Bob131** [comment]
:+1:

**Comment by arteymix** [comment]
Just removed the bad commit on tip of `master` so that we can get a result from the CI.

**Comment by arteymix** [comment]
@Bob131 do you think that providing the number of written bytes would be a useful out parameter?

**Comment by arteymix** [comment]
I'm even considering a `expand_printf` function, but that won't be of much use though.

**Comment by Bob131** [comment]
Not really. I can't really imagine any real use case for it

**Pull request merged**
