### PR TITLE
Meson build

### PR DESCRIPTION
**Pull request by arteymix**
This PR migrate the build system to Meson.

There's a few blockers:

- [x]  pkg-config is not generating the `Requires` (in progress...)
- [x]  `add_global_arguments` is broken for Vala (fix in progress...)
- [x]  CLI arguments to enable the docs and examples
- [x]  RPM packaging
- [x]  building on 12.04 (might not be possible at all) (way too impossible!)
- [ ] find a replacement for `./waf dist`
- [x] `--debug` with coverage (see https://github.com/mesonbuild/meson/pull/500)
- [ ] support for Genie
- [x] install VAPI and GIR (see https://github.com/mesonbuild/meson/issues/505)
- [x] generate 
- [x] feature detection (eg. test dependency version)

Upstream details here: https://github.com/mesonbuild/meson/issues/487

### CODE REVIEW

**Comment by arteymix** [comment]
Since Meson require Python 3.4+, we cannot build on Ubuntu 12.04.

**Comment by jpakkane** [comment]
Some minor issues:

    add_global_arguments(['-Wall',

You don't need this, Meson will add it for you (except when buildtype is plain, but this usually only happens on distro package builds where -Wall comes in from CFLAGS). Depending on your needs you might also want to increase the default warning level instead of adding extra warnings by hand.

The current spec file does not work the way you expect it to. You might want to swipe a working configure stanza from [the sample rpmmacro we have](https://github.com/mesonbuild/meson/blob/master/data/macros.meson).

**Comment by arteymix** [comment]
@jpakkane actually, I suppress warnings that cannot be addressed in Vala

I did not see the RPM macros, it's always nice to have :+1: and for the flags, I simply copied what I had in the `wscript`.

Now, I'm wondering how I will be able to build on the Copr. Do you backport fixes?

On the other hand, I think I will abandon the idea of running Meson on 12.04, because it just seem very difficult to overcome the dependencies.

**Comment by arteymix** [comment]
The CI is kind of stuck at "Waiting for status to be reported", so I'll reopen the ticket..

**Comment by arteymix** [comment]
I added a custom script for installing bindings and dependency files.

**Comment by arteymix** [comment]
The 0.32 will introduce helpers to test dependency version and fix feature detection.

**Comment by arteymix** [comment]
From now on, we have to be careful because we are not building on minimal dependencies and there should be some check before releases.

The Docker build still have to be updated.

**Pull request closed without merging**
