### PR TITLE
Spec fix

### PR DESCRIPTION
**Pull request by Bob131**
Sorry if I'm overstepping editing your gitignore, if so cherry-picking that last commit should do the trick. I tested this just now and it builds in Copr a-ok. Also, the source URL is a valid URL, so now you can build with the slightly less arduous ```spectool -g -R build/valum.spec; rpmbuild -bs build/valum.spec```

### CODE REVIEW

**Comment by Bob131** [comment]
Hopefully this new commit addresses your concerns. Thank you for your patience in explaining your reasoning; you may have just made me a `waf` convert :)

**Comment by arteymix** [comment]
Waf is really a nice build system once you get a good grasp of it.

Aside all this, what are your thoughts about the framework? I am very interested in feedback to schedule the features for the next minor release.

**Comment by Bob131** [comment]
Well, I was actually waiting for a build on Copr before I tried it out. I've a fair amount of experience with the excellent Flask framework, and so I was kind of imagining something similar but without the heavy performance cost of the CPython VM. Once I've had a little while to play with it, I'd be more than happy to share my thoughts in a new ticket! Vala is a platform I've discovered a great passion for, and I think a cross-platform web microframework has the potential to drive a lot more interest and enthusiasm for it :)

**Comment by arteymix** [comment]
@Bob131 I just updated the documentation generation, it's now _optionally_ part of the build process.

**Comment by arteymix** [comment]
@Bob131 I picked the changes for the specfile and I am running a Copr build as of right now. I'll push everything when it succeeds

**Comment by arteymix** [comment]
@Bob131 It works nicely by the way!

**Comment by Bob131** [comment]
Sweet! I look forward to contributing some more in the not-to-distant future :)

**Comment by arteymix** [comment]
Functionally speaking, there's a tons of things to do:

 - middlewares (step in the routing)
 - filters (transform `Request` and `Response` object by composition)
 - typed parameters using `Type` and `Value`
 - examples using various external libraries

I opened issues or PRs for these ideas if you want to dig a little.

The `0.2` really set the basis to build all the components of a general purpose web framework I would like Valum to become someday.

**Pull request closed without merging**
