### PR TITLE
VSGI loader for GModule-based applications

### PR DESCRIPTION
**Pull request by arteymix**
This PR provides a new utility named `vsgi` to serve application written as a GModule using any supported server technology (`soup`, `scgi` and `fastcgi`)

If `libapp.so` is installed in standard location:

``` bash
vsgi app:app
```

Server-specific arguments are passed after the `--`

``` bash
vsgi app:app -- --port=3003
```

The only constaint for a compliant application is to provide a symbol following the `ApplicationCallback` delegate.

``` vala
using VSGI;

public void app (Request req, Response res) {
    // ...
}
```

GModule provides static loading and unloading with `g_module_check_init` and `g_module_unload` symbols.

### CODE REVIEW

**Comment by arteymix** [comment]
The `--application-id` option requires the `VSGI.Server` to accept `null` application identifiers.

**Comment by arteymix** [comment]
The `vsgi` program should have a proper manpage.

The error message should be more helpful and propose a call with `--help` to obtain more details.

**Comment by arteymix** [comment]
With the rebase, `vsgi` is now statically bind with `libvalum`.

**Comment by arteymix** [comment]
Just a note: the GModule init loading and unloading can be used to perform live reloading.

**Comment by arteymix** [comment]
This should be rebased upon 3b94bb8 to load VSGI implementations dynamically.

**Comment by arteymix** [comment]
It would be nice to support `SIGHUP` for reloading.

**Comment by arteymix** [comment]
Modules cannot be installed directly in `lib`.. They must be relocated in a specific folder like `lib/vsgi/servers`.

**Comment by Bob131** [comment]
I just wanted to raise the possibility of some sort of configuration middleware whereby the `vsgi` utility could read from a config file rather than requiring CLI args, as well as passing some of those options onto the GModule app. Without such a mechanism, it seems as though daemonising apps with the need for their own configs with `vsgi` would become quite messy

**Comment by arteymix** [comment]
The CLI is only a facility for passing arguments and setting up the server minimally. I added the `listen` and `fork` call a few weeks ago to make that simpler.

Each implementation interpret its options as a `Variant` object, so it could be possible to specify a config blob to load. However, doing so would mean to ignore arguments passed the `--` delimiter.

```bash
vsgi --config some-blob.bin app:app
```

That would require tools for converting JSON (or any useful format) to GVariant.

**Comment by arteymix** [comment]
I plan to first convert server implementations to GModule and then merge this PR.

We should have something like that instead (given `/usr/lib64/vsgi/servers/libvsgi-http.so`):

```vala
Server.@new ("http", "org.valum.Example", () => {});
```

Also some `ServerModule` API to handle more customizable use cases.

**Comment by arteymix** [comment]
The work should be rebased on #182. It will remove the hard-coded implementation switch.

**Comment by arteymix** [comment]
Having a ``HandlerCallback`` signal defined in the module is not very practical because we have to initialize everything statically. I think that it would be best to define a ``ModuleCallback`` as follow:

```vala
public delegate ApplicationCallback ModuleCallback ();
```

```vala
public ApplicationCallback my_modular_app () {
    // put shared states here (e.g. database pool)
    return (req, res) => {
        return res.expand_utf8 ("Hello world!");
    };
}

public ApplicationCallback my_modular_router () {
    var app = new Router ();

    app.get ("/", (req, res) => {
        return res.expand_utf8 ("Hello world");
    });

    return app.handle;
}
```

**Pull request merged**
