### PR TITLE
Add a middleware for promoting a connection to WebSocket (fix #205)

### LINKED ISSUE #205: WebSocket backend for VSGI
Currently, libsoup-2.4 supports the WebSocket protocol and we could very well provide a server implementation that would use it as a transport layer. Once the handshake is initiated, the body streams would become suitable for passing messages.

Each flushed `write_all` (e.g. `append` and `append_utf8`) would become a message and we could extend the current request API to read a "chunk" of data.

### PR DESCRIPTION
**Pull request by arteymix**

### CODE REVIEW

**Comment by ZanderBrown** [comment]
Any chance of resurrecting this?

**Comment by arteymix** [comment]
I'll look into it tomorrow.

**Comment by arteymix** [comment]
I just tester the handshake so far, but I'll write a unit test using the client that comes with libsoup-2.4.

**Comment by ZanderBrown** [comment]
Looking good, been wanting to have a serious play with valum for a while and I now find myself needing a WebSocket server. Having looked at the insanity of doing that in PHP it seemed as good a time as any to finally get valum out.

**Comment by ZanderBrown** [comment]
Anything I could do to push this over the line?

**Comment by arteymix** [comment]
I finally managed to make it work! I'll push the testcase in a few hours (I have a course now).

**Comment by arteymix** [comment]
I wrote the test case against the example, but I'll complete it later. Meanwhile, you can test it and give it some feedback.

I'll try to fix the CI..

**Comment by ZanderBrown** [comment]
Seem to have run into some problems that seem to be around valum expecting `http://` but (at least in js) only `ws://`(or `wss://`) is valid for WebSocket connections.

Also ninja seems to timeout on the websocket test and my simple soup client reports
```
The server did not accept the WebSocket handshake.
```

**Comment by ZanderBrown** [comment]
Okay pulled latest commit, now I get
```
ERROR:websocket-test.vala:18:__lambda5_: code should not be reached
```
For the test

**Comment by arteymix** [comment]
You need to start the example application to run the test until I include it in the unit test itself. I think I'll use a fork for starting the server part.

**Comment by arteymix** [comment]
I think I've found why it was not working, the `Connection` header can contains a param list.

I'll release a 0.4 with WebSocket support along with VSGI 1.0 soon after this get merged. I'd like to make it to the next TechEmpower benchmark!

**Comment by ZanderBrown** [comment]
Connecting to examples/app /websocket in JS seems to work for me now

**Comment by arteymix** [comment]
It was fixed in cea368da35759436d272a69d3beae2239c800b0f

Since it's working, I've merged the work into the trunk and I'll include the testcase later.

**Pull request closed without merging**
